keys:
  - &users:
    - &prescientmoon_tethys age14mga4r0xa82a2uus3wq5q7rqnvflms3jmhknz4f3hsda8wttk9gsv2k9fs
    - &prescientmoon_calypso age13c346xw9kzsvra04ck8h8pa47mwdp8nh3aess4pwhyvdsufyhf0qt65ja8
  - &hosts:
    - &tethys age1avsekqqyr62urdwtpfpt0ledzm49wy0rq7wcg3rnsprdx22er5usp0jxgs
    - &lapetus age1jem6jfkmfq54wzhqqhrnf786jsn5dmx82ewtt4vducac8m2fyukskun2p4
    - &calypso age18gengezksnt0wtc3sv28ypmx546quzeg88kw5s8sywxyje5rmqyqh9daxe
    - &hermes age1r2vlh9tgdmf6r0xj025zun0cvudn2p6jqav84pql8k928newtepq9ttw8z
creation_rules:
  - path_regex: hosts/nixos/common/secrets.yaml
    key_groups:
      - age:
        - *prescientmoon_tethys
        - *prescientmoon_calypso
        - *tethys
        - *lapetus
        - *calypso
        - *hermes
  - path_regex: hosts/nixos/lapetus/secrets.yaml
    key_groups:
      - age:
        - *prescientmoon_tethys
        - *prescientmoon_calypso
        - *lapetus
        - *hermes
  - path_regex: home/features/desktop/wakatime/secrets.yaml
    key_groups:
      - age:
        - *prescientmoon_tethys
        - *prescientmoon_calypso
        - *hermes
  - path_regex: home/features/cli/productivity/secrets.yaml
    key_groups:
      - age:
        - *prescientmoon_tethys
        - *prescientmoon_calypso
        - *hermes
